-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.menus
(
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    added_at timestamp without time zone NOT NULL,
    stock integer,
    description character varying(255),
    price money NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.order_lists
(
    order_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    is_complete boolean,
    order_at timestamp without time zone NOT NULL,
    PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    user_id integer NOT NULL,
    menu_id integer NOT NULL,
    jumlah integer NOT NULL,
    order_id integer
);

CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL,
    username character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    is_admin boolean NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.order_lists
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.orders
    ADD FOREIGN KEY (menu_id)
    REFERENCES public.menus (id)
    NOT VALID;


ALTER TABLE public.orders
    ADD FOREIGN KEY (order_id)
    REFERENCES public.order_lists (order_id)
    NOT VALID;


ALTER TABLE public.orders
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;

END;